name: Tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-13', 'windows-latest']
        python-version: ["3.7", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[all]
      - name: Test with pytest
        env:
          SOLCAST_API_KEY: ${{ secrets.SOLCAST_API_KEY }}
        run: |
          pytest tests
